name: Deploy Games 

on: 
  push: 
    branches: [main]

jobs:
  build: 
    runs-on: [ubuntu-latest]
    steps: 
      - name: Checkout source 
        uses: actions/checkout@v4
      - name: Login no docker
        run: echo ${{secrets.DOCKER_PASS}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin
      - name: Verificar espaço em disco
        run: |
          echo "Espaço em disco:"
          df -h
          if [ $(df / | tail -1 | awk '{print $4}') -lt 1000000 ]; then
            echo "Espaço em disco insuficiente!"
            exit 1
          fi  
      - name: Build Docker image 
        run: docker build -t mihkenia/games-deploy:latest .
      - name: Publicar a imagem da aplicação no docker hub 
        run: docker push mihkenia/games-deploy:latest

  deploy: 
    needs: build
    runs-on: [aws-ec2]
    steps: 
    - name: Criar network
      run: |
          if ! docker network ls | grep -q my-net; then
            docker network create my-net
          fi
    - name: Pull da imagem do postgres:16
      run: docker pull postgres:16
    - name: Criar/rodar o container do banco de dados      
      run: |
          if docker container inspect database-container &> /dev/null; then
            echo "O container já existe."
          else
            echo "O container não existe."   
            docker run -d --name database-container --network my-net -p 5432:5432 -e POSTGRES_DB=gamesdatabase -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres postgres:16
          fi
    - name: Pull da imagem da aplicação no Docker Hub
      run: docker pull mihkenia/games-deploy:latest
    - name: Deletar container do app existente
      run: |
          if docker container inspect app-container &> /dev/null; then
            docker rm -f app-container
          else
            echo "O container app-container não existe."
          fi
    - name: Criar/rodar o container da aplicação
      run: |
          set -e # Aborta se qualquer comando falhar
          docker run -d -p 3000:3000 --name app-container --network my-net \
          -e DB_URL="postgresql://postgres:postgres@database-container:5432/gamesdatabase?schema=public" \
          mihkenia/games-deploy:latest sh -c "npm run migration:run && npm run start"
    - name: Limpar imagens e contêineres não utilizados
      run: docker system prune -f --volumes 

      
